[project]
name = "clios"
version = "0.1.0"
description = "cliOS is a project that provides one-shot commands for faster cli actions and capturing ideas"
readme = "README.md"
authors = [
    { name = "Kesler", email = "uchekesla@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
run = "clios:main"

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"
